version: '3.8'

services:
  win_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: win_test
    volumes:
      - .:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: