version: '3.8'

services:
  win_test:
    container_name: win_test
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
    volumes:
      - .:/app:rw
    ports:
      - "8337:8337"
    environment:
      - APP_ENV=dev
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: